### ISSUE TITLE
Output counted number of characters for jinja templates

### ISSUE THREAD

**Issue by annegentle** [annegentle/wadl2rst#12]
The titles could have logic in the template so that it counts the number of characters and outputs the correct number of characters for the title. 

For example:

```
=============================================================================
{{title}}  -  {{book_title}}
=============================================================================

{{title}}
```

```

Currently outputs this:

```
# 
# Create Server -  OpenStack Compute API v2.1

Create Server

```
```

Could the template use the length of an object and output that number of `=` or `~`?

**Comment by missaugustina** [comment]
I found this in the jinja template:
{% for item in request_examples %}
{% endfor %}

I'm not sure what can be used in that loop but maybe we could have a title_length field and use the template to output the correct number of ~'s

**Comment by kbhawkey** [comment]
See my recent commit #6544929.
