### ISSUE TITLE
Not picking up resource-type

### ISSUE THREAD

**Issue by missaugustina** [annegentle/wadl2rst#20]

**Comment by missaugustina** [comment]
resource
resource_type

collapse_resources.py
resources_node = tree.find_first("resources")

should look just like resources

**Comment by missaugustina** [comment]
Here's an example of what this looks like in wadl:

```
<resource_type id="DetailServerList">
      <wadl:doc xmlns="http://docbook.org/ns/docbook" xml:lang="EN" title="Detail server list">
         <para>A detailed server list.</para>
      </wadl:doc>
      <method href="#listServersDetailed"/>
   </resource_type>
```

Right now, collapse_resources.py is just looking for things in the <resources> block but the resource_type stuff lives outside of that. It is linked however by id that indicates there's a resource_type entry in the XML for it.

`<resource id="server_detail" path="detail" type="#DetailServerList"/>`

I think we just need to add some logic in collapse_resources that looks for the additional resource_type nodes if there's a "type" attribute on the resource it's currently processing.

**Comment by annegentle** [comment]
Looks right to me. I think this is the root cause of Issue #7

**Comment by missaugustina** [comment]
I'm going to close this and open a new issue for the additional missing resource types since this basically gets us 90% of the way there.
