### ISSUE TITLE
Missing migrations for Compute resources

### ISSUE THREAD

**Issue by annegentle** [annegentle/wadl2rst#7]
Not sure why, but only this GET is migrated over: `GET /v2.1/{tenant_id}/servers/{server_id}` for the /servers resource.

**Comment by annegentle** [comment]
More research here. There are 207 files made now for 223 operations, found using the web scraper tool in this PR https://github.com/annegentle/wadl2rst/pull/14. Will dig in more.

**Comment by annegentle** [comment]
Ok, figured out one source of the problem. Any WADL file that has `<resource_type>` instead of `<resource>` and points to methods is ignored by the WADL2RST tool. After talking to writers at Rackspace, I think the best thing to do is to change the WADL from `<resource_type>` to `<resource>` and move the migration along. I'll submit patches to the openstack/api-site repo making these changes, which should then let us migrate completely.

**Comment by sdague** [comment]
+1 sounds great
