### ISSUE TITLE
Create a comma separated list of error codes

### ISSUE THREAD

**Issue by missaugustina** [annegentle/wadl2rst#9]

**Comment by annegentle** [comment]
I think Issue #6 might be what we want output, what does the comma-separated list give us that a solution to #6 does not?

**Comment by missaugustina** [comment]
I think it was just meant as a first pass option. But yeah, I'm happy to drop this one since it looks like you're working on it.

**Comment by annegentle** [comment]
I think it's okay to do the simplest first, which is to output a list of error codes. Could be simply for example:
- Success: 200, 202
- Errors Codes: 300, 302, 400, 401, 502

**Comment by missaugustina** [comment]
Normal response codes: 202

Error response codes: computeFault (400, 500, …), serviceUnavailable
(503), badRequest (400), unauthorized (401), forbidden (403),
badMethod (405), itemNotFound (404)

**Comment by missaugustina** [comment]
What we have is good enough, for future work, verify that data isn't missing, but if it's not then close this.

**Comment by annegentle** [comment]
Okay, sounds good.
